# Generated by Django 5.2.17 on 2026-09-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('telegram_chat_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('accent', models.CharField(default='#4A9BC7', max_length=16)),
                ('icon', models.CharField(default='people', max_length=32)),
                ('updated_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('telegram_message_id', models.BigIntegerField()),
                ('sender_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.BigIntegerField()),
                ('media_type', models.CharField(blank=True, max_length=32, null=True)),
                ('media_file', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatgroup')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['group', '-created_at'], name='idx_messages_group_created')],
                'constraints': [models.UniqueConstraint(fields=('group', 'telegram_message_id'), name='uniq_group_telegram_message')],
            },
        ),
    ]
