# Generated by Django 5.2.17 on 2026-09-13 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('surah', 'Surə'), ('ayah', 'Ayə')], default='surah', max_length=8)),
                ('surah', models.PositiveSmallIntegerField()),
                ('ayah', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['surah', 'ayah'], name='dashboard_s_surah_4b7dab_idx')],
            },
        ),
    ]
