# Generated by Django 5.2.17 on 2026-09-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_word_mark_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmarknote',
            name='direction',
            field=models.CharField(choices=[('istinaf_first', 'İstinaf → Vəqf'), ('waqf_first', 'Vəqf → İstinaf')], default='istinaf_first', max_length=20),
        ),
    ]
