# /etc/nginx/sites-available/... — quran-backend
# root ≠ alias: static Django collectstatic → staticfiles/

server {
    listen 80;
    server_name 164.90.165.24;

    location = /favicon.ico { access_log off; log_not_found off; }

    # /static/admin/... → /var/www/quran-backend/staticfiles/admin/...
    location /static/ {
        alias /var/www/quran-backend/staticfiles/;
        access_log off;
        expires 7d;
    }

    # MEDIA_ROOT = DATA_DIR/media — əgər DATA_DIR=/var/www/quran-backend/data
    location /media/ {
        alias /var/www/quran-backend/data/media/;
        access_log off;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/quran-backend/gunicorn.sock;
    }
}
